spring.application.name=OnlineVegApplications
spring.datasource.url=jdbc:postgresql://localhost:5432/Application
spring.datasource.username=postgres
spring.datasource.password=Tadipatri@12
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update